config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  get 'task/:id/assign' => 'tasks#assign', as: 'assign_task'
  patch 'task/:id/assign' => 'tasks#update_assignment', as: 'update_assignment'
  get 'tasks/mine' => 'tasks#my_tasks'
  resources :tasks

  devise_for :users

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :status, presence: true
  validates :deadline, presence: true

  belongs_to :user, required: false
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  enum statuses: {
    waiting: 0,
    doing: 1,
    done: 2
  }

  STATUS_NAME = {
    Task.statuses[:waiting] => '未対応',
    Task.statuses[:doing] => '対応中',
    Task.statuses[:done] => '完了'
  }

  def get_status_str
    STATUS_NAME[self.status]
  end

  def is_created_by?(user)
    self.author == user
  end

  def is_outdated?
    if self.deadline.nil?
      return false
    end
    return self.deadline < Time.current
  end

  scope :index_all, -> {
    all
      .order(created_at: :asc)
      .where.not(status: Task.statuses[:done])
      .includes(:user)
  }

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :tasks, foreign_key: 'author_id', class_name: 'Task', dependent: :destroy #destroyじゃないようにもできるようにしたい
  has_many :tasks_to_do, foreign_key: 'user_id', class_name: 'Task', dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy assign update_assignment]
  before_action :authenticate_user!

  # GET /tasks or /tasks.json
  def index
    @selected_user = get_selected_user_from_params
    @tasks = eval(generate_method_chain_str_to_get_specific_tasks)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.author_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_tasks
    @tasks = Task.index_all.where(author_id: current_user)
  end

  def assign
  end

  def update_assignment
    if @task.update(assignment_params)
      redirect_to task_url(@task.id)
    else
      render :assign, status: :unprocessable_entity
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :content, :status, :deadline)
  end

  def assignment_params
    params.require(:task).permit(:user_id)
  end

  def generate_method_chain_str_to_get_specific_tasks
    method_chain_str = "Task.all"

    if params[:comp_tasks].nil?
      method_chain_str += ".where.not(status: Task.statuses[:done])"
    end
    if params[:list_desc]
      method_chain_str += ".order(created_at: :desc)"
    end
    if params[:tasks_mine]
      method_chain_str += ".where(user_id: current_user)"
    end
    if params[:task_assignee].present? && params[:task_assignee][:user_id].present?
      task_assignee = params[:task_assignee][:user_id]
      if User.all.where(id: task_assignee).present?
        method_chain_str += ".where(user_id: #{task_assignee})"
      end
    end
    if params[:outdated_tasks]
      method_chain_str += ".where(deadline: ..Time.current)"
    end

    method_chain_str += ".includes(:user)"
    return method_chain_str
  end

  def get_selected_user_from_params
    if params[:task_assignee].present? && params[:task_assignee][:user_id].present?
      selected_user_id = params[:task_assignee][:user_id]
      if User.all.where(id: selected_user_id).present?
        return selected_user_id
      end
    end
    return nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
  <h2>
    <a href="/" , id="header-title">タスク管理アプリ</a>
  </h2>
  <nav>
    <ul>
      <li id="unordered-list">
      <li><%= link_to 'マイタスク', tasks_mine_path, class: "header-col" %></li>
      <li><%= link_to 'タスク一覧', tasks_path, class: "header-col" %></li>
      <li><%= link_to 'ユーザ設定', edit_user_registration_path, class: "header-col" %></li>
      <li id="sign-in-out">
        <% if user_signed_in? %>
          <%= link_to 'サインアウト', destroy_user_session_path, method: :delete, data: { confirm: "サインアウトしてもよろしいですか？" }, class: "sign-in-out-col" %>
        <% else %>
          <%= link_to 'サインイン', new_user_session_path, class: "sign-in-out-col" %>
        <% end %>
      </li>
    </ul>
  </nav>
  <nav id="welcome-msg">
    <ul>
      <% if user_signed_in? %>
        <li>
          <span>ようこそ<%= current_user.name.nil? ? current_user.email : current_user.name %>さん</span>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="whole-site">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <strong><%= form.label :Title %></strong>
    <%= form.text_field :title, class: "text-field" %>
  </div>

  <div class="field">
    <strong><%= form.label :Content %></strong>
    <%= form.text_area :content, class: "text-field" %>
  </div>

  <div class="field">
    <strong><%= form.label :Deadline %><br></strong>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="field">
    <strong><%= form.label :Status %></strong>
    <%= form.radio_button :status, Task.statuses[:waiting], checked: true %>
    <%= form.label "未対応" %>
    <%= form.radio_button :status, Task.statuses[:doing] %>
    <%= form.label "対応中" %>
    <% if local_assigns[:edit] %>
      <%= form.radio_button :status, Task.statuses[:done] %>
      <%= form.label "完了" %>
    <% end %>
  </div>

  <div class="actions">
    <% if local_assigns[:edit] %>
      <%= form.submit '更新する', class: "btn btn-success" %>
      <%= link_to '一覧へ戻る', tasks_path, class: "btn btn-outline-secondary" %>
    <% else %>
      <%= form.submit '登録する', class: "btn btn-success" %>
    <% end %>
  </div>
<% end %>

app/views/tasks/_index_page.html.erb
<div class="row">
  <% if @tasks.empty? %>
    <div>There seems to be no tasks....</div>
  <% end %>
  <% @tasks.each do |task| %>

    <div class="surroundings col-xs-12 col-md-6">
      <% task_class_suffix = task.is_outdated? ? "outdated" : "normal" %>
      <div class="task-border-<%= task_class_suffix %>">
        <div class="task-title-<%= task_class_suffix %>"><%= task.title %></div>
        <div class="task-body-<%= task_class_suffix %>">
          <span><%= task.content %></span><br>
          <span>期限：<%= task.deadline %></span><br><br>
          <span>担当者：<%= task.user&.email %></span><br><br>
          <span>ステータス：<%= task.get_status_str %></span><br>
          <span><%= link_to '詳細', task, class: "btn btn-outline-secondary" %></span>
          <% if task.is_created_by?(current_user) %>
            <span><%= link_to '編集', edit_task_path(task), class: "btn btn-info text-black" %></span>
            <span><%= link_to '削除', task, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger text-black" %></span>
          <% end %>
        </div>
      </div>

    </div>
  <% end %>
</div>

app/views/tasks/_task_detail.html.erb
<div class="task-detail-plate">
  <div>
    <h1> <%= @task.title %> </h1>
    <div> <%= simple_format(@task.content) %> </div>
    <div> 期限： <%= @task.deadline %> </div>

    <% if local_assigns[:show] %>
      <div> 担当者： <%= @task.user&.email %> </div>
    <% end %>

    <div> ステータス： <%= @task.get_status_str %> </div>
    <%= link_to '一覧へ戻る', tasks_path, class: "btn btn-outline-secondary bg-white" %>

    <% if local_assigns[:show] %>
      <% if @task.is_created_by?(current_user) %>
        <%= link_to '編集', edit_task_path(@task), class: "btn btn-info text-black" %>
        <%= link_to 'アサイン', assign_task_path, class: "btn btn-success text-white" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/assign.html.erb
<h1>アサイン</h1>
<%= form_for @task, url: { action: 'update_assignment' } do |f| %>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <span>現在アサインされているユーザ</span><br>
      <span><%= @task.user_id.nil? ? "誰にもアサインされていません" : @task.user.name %></span>
    </div>

    <div class="col-xs-12 col-md-6">
      <span>新しくアサインするユーザ</span><br>
      <%= f.collection_select :user_id, User.all, :id, :name, {}, { class: "assigner-selection" } %>
    </div>
  </div>
  <%= f.submit 'アサインする', class: "btn btn-success assign-btn" %>
<% end %>

<%= render 'task_detail' %>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render 'form', task: @task, edit: true %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>タスク一覧</h1>

  <%= form_tag tasks_path, method: :get do %>
    <%= check_box_tag :outdated_tasks, true, params[:outdated_tasks].present? ? true : false %>
    <%= label_tag :outdated_tasks, '期限切れタスクのみを表示' %><br>
    <%= check_box_tag :comp_tasks, true, params[:comp_tasks].present? ? true : false %>
    <%= label_tag :comp_tasks, '完了タスクも表示する' %><br>
    <%= check_box_tag :list_desc, true, params[:list_desc].present? ? true : false %>
    <%= label_tag :list_desc, '新しい順で並べる' %><br>
    <%= collection_select :task_assignee, :user_id, User.all, :id, :name, include_blank: true, selected: @selected_user %>
    <%= label_tag :task_assignee, 'に割り当てられたタスクを表示' %><br>
    <%= submit_tag '検索', name: nil %>
  <% end %>

  <%= render 'index_page' %>
</div>

app/views/tasks/my_tasks.html.erb
<div class="container">
  <h1>マイタスク</h1>
  <%= link_to 'New Task', new_task_path, class: "btn btn-outline-secondary" %>
  <%= render 'index_page' %>
</div>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<%= render 'task_detail', show: true %>